# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'database_management_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from module_1.layout_cameratab import Ui_MainWindow as Ui_CameraTab
from module_1.layout_modeltab import Ui_MainWindow as Ui_ModelTab
from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QMainWindow, QWidget, QLabel, QLineEdit, 
                             QVBoxLayout, QHBoxLayout, QGridLayout, QPushButton, 
                             QFrame, QComboBox, QScrollArea, QMessageBox, QSpinBox,
                             QTabWidget, QTableWidget, QTableWidgetItem, QHeaderView,
                             QGroupBox)
from PyQt5.QtCore import Qt, QSize
from PyQt5.QtGui import QFont, QIcon, QPixmap
from module_1.mysql_connnector import Ui_MainWindow as Ui_MySQLConnector
import mysql.connector
from mysql.connector import Error
from module_1.MySQL_WorkBench import Connect2Mysql
from module_1.from_confirm_dataset import Ui_MainWindow as FormConfirmTable
from module_3.main_thread import intermediate_layer
import sys

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 911)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/gui_part_legion/module_3/assert/icon/save-data.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/gui_part_legion/module_3/assert/icon/view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/gui_part_legion/module_3/assert/icon/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/gui_part_legion/module_3/assert/icon/system-update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.gridLayout_4.addWidget(self.frame_2, 4, 0, 1, 1)
        self.heading = QtWidgets.QLabel(self.centralwidget)
        self.heading.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.heading.setFont(font)
        self.heading.setFrameShape(QtWidgets.QFrame.Box)
        self.heading.setFrameShadow(QtWidgets.QFrame.Raised)
        self.heading.setTextFormat(QtCore.Qt.RichText)
        self.heading.setAlignment(QtCore.Qt.AlignCenter)
        self.heading.setObjectName("heading")
        self.gridLayout_4.addWidget(self.heading, 0, 0, 1, 1)
        self.groupBox_namedevice_itemcode = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_namedevice_itemcode.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_namedevice_itemcode.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_namedevice_itemcode.setFont(font)
        self.groupBox_namedevice_itemcode.setObjectName("groupBox_namedevice_itemcode")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_namedevice_itemcode)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_namedevice_itemcode)
        self.pushButton.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setIconSize(QtCore.QSize(16, 16))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setEnabled(False)
        self.gridLayout_2.addWidget(self.pushButton, 0, 2, 1, 1)
        self.lineEdit_name_devic = QtWidgets.QLineEdit(self.groupBox_namedevice_itemcode)
        self.lineEdit_name_devic.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_name_devic.setFont(font)
        self.lineEdit_name_devic.setObjectName("lineEdit_name_devic")
        self.gridLayout_2.addWidget(self.lineEdit_name_devic, 0, 1, 1, 1)
        self.label_quanty_itemcode = QtWidgets.QLabel(self.groupBox_namedevice_itemcode)
        self.label_quanty_itemcode.setMaximumSize(QtCore.QSize(115, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_quanty_itemcode.setFont(font)
        self.label_quanty_itemcode.setObjectName("label_quanty_itemcode")
        self.gridLayout_2.addWidget(self.label_quanty_itemcode, 1, 0, 1, 1)
        self.label_name_device = QtWidgets.QLabel(self.groupBox_namedevice_itemcode)
        self.label_name_device.setMaximumSize(QtCore.QSize(115, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_name_device.setFont(font)
        self.label_name_device.setObjectName("label_name_device")
        self.gridLayout_2.addWidget(self.label_name_device, 0, 0, 1, 1)
        self.spinBox_num_itemcode = QtWidgets.QSpinBox(self.groupBox_namedevice_itemcode)
        self.spinBox_num_itemcode.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox_num_itemcode.setFont(font)
        self.spinBox_num_itemcode.setObjectName("spinBox_num_itemcode")
        self.spinBox_num_itemcode.valueChanged.connect(self.update_quanty_codes)
        self.gridLayout_2.addWidget(self.spinBox_num_itemcode, 1, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_namedevice_itemcode)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/gui_part_legion/module_3/assert/icon/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(50, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 0, 3, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_namedevice_itemcode, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(115, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.setEnabled(False)
        self.gridLayout.addWidget(self.pushButton_8, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(115, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:/gui_part_legion/module_3/assert/icon/gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon5)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 2, 1, 1)
        self.label_test_ip_connection = QtWidgets.QLabel(self.groupBox)
        self.label_test_ip_connection.setFrameShape(QtWidgets.QFrame.Box)
        self.label_test_ip_connection.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_test_ip_connection.setText("")
        self.label_test_ip_connection.setAlignment(QtCore.Qt.AlignCenter)
        self.label_test_ip_connection.setObjectName("label_test_ip_connection")
        self.gridLayout.addWidget(self.label_test_ip_connection, 1, 2, 1, 2)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:/gui_part_legion/module_3/assert/icon/configuration.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon6)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 2, 0, 1, 1)
        self.tab_item_code = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_item_code.setMaximumSize(QtCore.QSize(16777215, 530))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tab_item_code.setFont(font)
        self.tab_item_code.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_item_code.setObjectName("tab_item_code")
        self.tab_itemcode_1 = QtWidgets.QWidget()
        self.tab_itemcode_1.setObjectName("tab_itemcode_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_itemcode_1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tab_item_code.addTab(self.tab_itemcode_1, "")
        self.tab_itemcode_2 = QtWidgets.QWidget()
        self.tab_itemcode_2.setObjectName("tab_itemcode_2")
        self.tab_item_code.addTab(self.tab_itemcode_2, "")
        self.gridLayout_4.addWidget(self.tab_item_code, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_item_code.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.update_quanty_codes()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Lưu cấu hình"))
        self.pushButton_3.setText(_translate("MainWindow", "Xem trước"))
        self.pushButton_4.setText(_translate("MainWindow", "Xóa tùy chọn"))
        self.pushButton_6.setText(_translate("MainWindow", "Cập nhật và Thoát"))
        self.heading.setText(_translate("MainWindow", "DATABASE MANAGEMENT CONTROL"))
        self.groupBox_namedevice_itemcode.setTitle(_translate("MainWindow", "Management Database"))
        self.pushButton.setText(_translate("MainWindow", "Xác nhận"))
        self.label_quanty_itemcode.setText(_translate("MainWindow", "Số lượng mã hàng:"))
        self.label_name_device.setText(_translate("MainWindow", "Tên thiết bị:"))
        self.groupBox.setTitle(_translate("MainWindow", "Establish connection to PLC"))
        self.label_2.setText(_translate("MainWindow", "PORT:"))
        self.pushButton_8.setText(_translate("MainWindow", "Xác nhận"))
        self.label.setText(_translate("MainWindow", "TCP/IP to PLC:        "))
        self.pushButton_7.setText(_translate("MainWindow", " Ping "))
        self.pushButton_9.setText(_translate("MainWindow", "IP CONFIG"))
        # self.tab_item_code.setTabText(self.tab_item_code.indexOf(self.tab_itemcode_1), _translate("MainWindow", "Mã hàng 1"))
        # self.tab_item_code.setTabText(self.tab_item_code.indexOf(self.tab_itemcode_2), _translate("MainWindow", "Mã hàng 2"))


    def update_quanty_codes(self):
        self.tab_item_code.clear()
        self.tab_windows = [] 
        self.tab_uis = []    
        for i in range(self.spinBox_num_itemcode.value()):
            self.core_ui = QtWidgets.QMainWindow()
            self.tab_itemcode_1 = Ui_CameraTab()
            self.tab_windows.append(self.core_ui)
            self.tab_uis.append(self.tab_itemcode_1)
            self.tab_itemcode_1.setupUi(self.core_ui)
            self.tab_item_code.addTab(self.core_ui, f'No.{i+1}')

    def closeEvent(self,event):
        event.close()

 
class QTableData:
    def __init__(self, ui):
        self.ui = ui
        self.cfm = False
        
    def save_config(self):
        self.save_data()
        self.cfm = True

    def save_data(self):
        self.list_item_code = {} 
        if not self.ui.lineEdit_name_devic.text():
            QMessageBox.warning(None, "Thông báo", "Vui lòng nhập tên máy!")
            return
        
        if not self.ui.tab_itemcode_1.lineEdit_name_itemcod.text():
            QMessageBox.warning(None, "Thông báo", "Vui lòng nhập tên mã hàng!")
            return
        
        for form in self.ui.tab_uis:
            product_data = form.take_data()
            self.list_item_code[product_data["product_codes"]] = product_data["camera_tabs"]
            if product_data["product_codes"]: 
                self.list_item_code[product_data["product_codes"]] = {
                    "device_name": self.ui.lineEdit_name_devic.text(),
                    "camera_tabs": product_data["camera_tabs"]
                }
            
        print("Dữ liệu đã lưu:", self.list_item_code)
        
        QMessageBox.information(None, "Thông báo", "Lưu thông tin thành công!")

    def view_data_from_ui(self):
        if not self.cfm:
            QMessageBox.warning(None, "Thông báo", "Vui lòng lưu cấu hình trước khi xem trước!")
            return
        self.cfm = False
        self.data_window = QMainWindow()
        self.data_window.setWindowTitle("Thông tin chi tiết")
        self.data_window.setMinimumSize(878, 718)
        
        central_widget = QWidget()
        layout = QVBoxLayout(central_widget)
   
        machine_info = QLabel(f"Thông tin máy: {self.ui.lineEdit_name_devic.text()}")
        machine_info.setFont(QFont("Arial", 14, QFont.Bold))
        machine_info.setAlignment(Qt.AlignCenter)
        layout.addWidget(machine_info)
        tab_widget = QTabWidget()
        
        for i, form in enumerate(self.ui.tab_uis):
            product_data = form.take_data()
            if product_data['product_codes'] == "":
                QMessageBox.information(None, "Thông báo", "Không có item code được chọn!")
                return
            else:
                product_tab = QWidget()
                product_layout = QVBoxLayout(product_tab)
                product_title = QLabel(f"Mã hàng: {product_data['product_codes']}")
                product_title.setFont(QFont("Arial", 12, QFont.Bold))
                product_layout.addWidget(product_title)
                table = QTableWidget()
                table.setRowCount(len(product_data["camera_tabs"]))
                table.setColumnCount(6)
                table.setHorizontalHeaderLabels(["No.","Camera", "Serial", "Địa chỉ IP", "Cổng kết nối", "Số lượng model"])
                for i in range(table.columnCount()):
                    table.horizontalHeader().setSectionResizeMode(i, QHeaderView.Stretch)
                table.verticalHeader().setVisible(False)
                table.setGeometry(QtCore.QRect(10, 10, 1181, 951))
                for row, camera_data in enumerate(product_data["camera_tabs"]):
                    table.setItem(row, 0, QTableWidgetItem(f'Camera {str(row + 1)}'))
                    table.setItem(row, 1, QTableWidgetItem(camera_data["camera_type"]))
                    table.setItem(row, 2, QTableWidgetItem(camera_data["serial"]))
                    table.setItem(row, 3, QTableWidgetItem(camera_data["ip_address"]))
                    table.setItem(row, 4, QTableWidgetItem(camera_data["port"]))
                    table.setItem(row, 5, QTableWidgetItem(str((camera_data["model_count"]))))
                product_layout.addWidget(table)
                tab_widget.addTab(product_tab, product_data["product_codes"])
            layout.addWidget(tab_widget)
        self.confirm_insert = QPushButton("Xác nhận")
        close_button = QPushButton("Close")
        close_button.clicked.connect(self.data_window.close)
        layout.addWidget(close_button, alignment=Qt.AlignRight)
        layout.addWidget(self.confirm_insert, alignment=Qt.AlignRight)
        self.data_window.setCentralWidget(central_widget)
        self.data_window.show()

    def view_data_from_dict(self):
        if not hasattr(self, 'list_item_code') or not self.list_item_code:
            QMessageBox.warning(None, "Thông báo", "Không có dữ liệu thiết bị để hiển thị!")
            return

        self.data_window = QMainWindow()
        self.data_window.setWindowTitle("Thông tin chi tiết")
        self.data_window.setMinimumSize(878, 718)

        central_widget = QWidget()
        layout = QVBoxLayout(central_widget)

        machine_info = QLabel("Thông tin thiết bị")
        machine_info.setFont(QFont("Arial", 14, QFont.Weight.Bold))
        machine_info.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(machine_info)

        tab_widget = QTabWidget()

        for device_name, device_data in self.list_item_code.items():
            product_tab = QWidget()
            product_layout = QVBoxLayout(product_tab)
            product_title = QLabel(f"Mã hàng: {device_name}")
            product_title.setFont(QFont("Arial", 12, QFont.Weight.Bold))
            product_layout.addWidget(product_title)

            table = QTableWidget()
            camera_list = device_data.get("camera_tabs", [])
            table.setRowCount(len(camera_list))
            table.setColumnCount(6)
            table.setHorizontalHeaderLabels(["No.", "Camera", "Serial", "Địa chỉ IP", "Cổng kết nối", "Số lượng model"])
            
            for i in range(table.columnCount()):
                table.horizontalHeader().setSectionResizeMode(i, QHeaderView.ResizeMode.Stretch)
            table.verticalHeader().setVisible(False)

            for row, camera_data in enumerate(camera_list):
                table.setItem(row, 0, QTableWidgetItem(f'Camera {str(row + 1)}'))
                table.setItem(row, 1, QTableWidgetItem(camera_data.get("camera_type", "N/A")))
                table.setItem(row, 2, QTableWidgetItem(camera_data.get("serial", "N/A")))
                table.setItem(row, 3, QTableWidgetItem(camera_data.get("ip_address", "N/A")))
                table.setItem(row, 4, QTableWidgetItem(camera_data.get("port", "N/A")))
                table.setItem(row, 5, QTableWidgetItem(str(camera_data.get("model_count", "N/A"))))
            
            product_layout.addWidget(table)
            tab_widget.addTab(product_tab, device_name)
        
        layout.addWidget(tab_widget)

        confirm_insert = QPushButton("Xác nhận")
        confirm_insert.clicked.connect(self.connectnsert_data)
        close_button = QPushButton("Close")
        close_button.clicked.connect(self.data_window.close)
        
        layout.addWidget(close_button, alignment=Qt.AlignmentFlag.AlignRight)
        layout.addWidget(confirm_insert, alignment=Qt.AlignmentFlag.AlignRight)
        
        self.data_window.setCentralWidget(central_widget)
        self.data_window.show()


    def clear_data(self):
        reply = QMessageBox.question(
            None, "Xác nhận", "Bạn có chắc muốn xóa tất cả dữ liệu?",
            QMessageBox.Yes | QMessageBox.No, QMessageBox.No
        )
        if reply == QMessageBox.Yes:
            self.ui.lineEdit_name_devic.clear()
            self.ui.spinBox_num_itemcode.setValue(1)
            self.ui.update_quanty_codes()
            QMessageBox.information(None, "Thông báo", "Đã xóa tất cả dữ liệu!")

    def insert_data(self):
       pass


class Pyuic5():
    def __init__(self,ui_db):
        import ctypes
        ctypes.windll.shcore.SetProcessDpiAwareness(1)
        QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
        QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)
        self.ui_db = ui_db

        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.MainWindow)

        self.mysqlWindow = QtWidgets.QMainWindow()
        self.mysqlUi = Ui_MySQLConnector()
        self.mysqlUi.setupUi(self.mysqlWindow)

        self.formmysqlWindow = QtWidgets.QMainWindow()
        self.form_mysql = FormConfirmTable(self.ui)
        self.form_mysql.setupUi(self.formmysqlWindow)

        self.connect = Connect2Mysql(self.mysqlUi, self.form_mysql, self.ui)

        self.mysqlUi.pushButton_cancel.clicked.connect(lambda _ , u=self.connect: u.connect_to_mysql())
        self.ui.pushButton_5.clicked.connect(lambda _ , u=self.mysqlWindow: u.show())
        self.ui.pushButton_2.clicked.connect(self.form_mysql.save_config)
        self.ui.pushButton_3.clicked.connect(self.formmysqlWindow.show)
        self.ui.pushButton_4.clicked.connect(self.form_mysql.clear_data)
        self.ui.pushButton.clicked.connect(self.connect.create_item_code_device)
        self.ui.pushButton_7.clicked.connect(self.connect.TCP_IP_PORT2PLC)
        self.ui.pushButton_9.clicked.connect(self.connect.ip_config)
        self.form_mysql.confirm_btn.clicked.connect(self.connect.commitment)
        self.ui.pushButton_6.clicked.connect(lambda:self.query_device(self.MainWindow))
        self.MainWindow.show()


    def query_device(self,event):
        db_submenu = QtWidgets.QMenu()
        self.cursor = self.connect.connection.cursor()
        self.cursor.execute("SHOW DATABASES") 
        databases = self.cursor.fetchall()
        for db_name in databases:
            db_name_str = db_name[0]
            QtWidgets.QAction(db_name_str, db_submenu)
            self.cursor.execute(f"USE {db_name_str}")
            self.cursor.execute(f"SHOW TABLES")
            tables = self.cursor.fetchall()
            for table in tables:
                if 'items_code' == table[0]:
                    self.cursor.execute(f"SELECT name_line_code FROM ITEMS_CODE")
                    item_codes = self.cursor.fetchall()
                    item_code_submenu = QtWidgets.QMenu(f"{db_name_str.upper()}", db_submenu)
                    for item_code in item_codes:
                        item_code_action = QtWidgets.QAction(item_code[0], item_code_submenu)
                        item_code_action.triggered.connect(lambda checked=False, code=item_code[0],db=db_name[0]: self.open_pyuic6(code,db))
                        item_code_submenu.addAction(item_code_action)
                    db_submenu.addMenu(item_code_submenu)
        self.ui_db.actionDevice_Name.setMenu(db_submenu) 
        self.ui.closeEvent(event)

    def open_pyuic6(self,i_code,db):
        self.pyuic6_instance = intermediate_layer(i_code,db,self.connect)
