# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mysql_connnector.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from module_1.layout_cameratab import Ui_MainWindow as Ui_CameraTab
from module_1.layout_modeltab import Ui_MainWindow as Ui_ModelTab
from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QMainWindow, QWidget, QLabel, QLineEdit, 
                             QVBoxLayout, QHBoxLayout, QGridLayout, QPushButton, 
                             QFrame, QComboBox, QScrollArea, QMessageBox, QSpinBox,
                             QTabWidget, QTableWidget, QTableWidgetItem, QHeaderView,
                             QGroupBox)
from PyQt5.QtCore import Qt, QSize
from PyQt5.QtGui import QFont, QIcon, QPixmap
import mysql.connector
from mysql.connector import Error
from module_1.MySQL_WorkBench import Connect2Mysql

class Ui_MainWindow(object):
    def __init__(self):
        super().__init__()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Connect to MySQL Server")
        MainWindow.resize(723, 263)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(400, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.frame_2.setFont(font)
        self.frame_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_testconnection = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_testconnection.setFont(font)
        self.pushButton_testconnection.setObjectName("pushButton_testconnection")
        self.horizontalLayout.addWidget(self.pushButton_testconnection)
        self.pushButton_cancel = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton_cancel.clicked.connect(MainWindow.close)
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.gridLayout.addWidget(self.frame_2, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.lineEdit_hostname = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_hostname.setFont(font)
        self.lineEdit_hostname.setObjectName("lineEdit_hostname")
        self.gridLayout_2.addWidget(self.lineEdit_hostname, 0, 1, 1, 1)
        self.lineEdit_port = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_port.setFont(font)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.gridLayout_2.addWidget(self.lineEdit_port, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_username = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.gridLayout_2.addWidget(self.lineEdit_username, 1, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_password = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.gridLayout_2.addWidget(self.lineEdit_password, 2, 1, 1, 3)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 723, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_testconnection.setText(_translate("MainWindow", "Test Connection"))
        self.pushButton_cancel.setText(_translate("MainWindow", "Exit"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.label_5.setText(_translate("MainWindow", "Name or IP adress of the Server host. "))
        self.label_7.setText(_translate("MainWindow", "The use\'s passwword."))
        self.label_6.setText(_translate("MainWindow", "Name of the user connect with."))
        self.label_4.setText(_translate("MainWindow", "Port:"))
        self.label.setText(_translate("MainWindow", "Hostname:"))
        self.label_2.setText(_translate("MainWindow", "Username"))
        self.lineEdit_hostname.setText(QtCore.QCoreApplication.translate("MainWindow", u"127.0.0.1", None))
        self.lineEdit_port.setText(QtCore.QCoreApplication.translate("MainWindow", u"3306", None))
        self.lineEdit_username.setText(QtCore.QCoreApplication.translate("MainWindow", u"root", None))
        
    def closeEvent(self, event):
        reply = QMessageBox.question(self, 'Message',
            "Are you sure to quit?", QMessageBox.Yes | 
            QMessageBox.No, QMessageBox.No)

        if reply == QMessageBox.Yes:
            event.accept()
        else:
            event.ignore()
