# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'automation_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import (QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout, 
                            QTableWidget, QTableWidgetItem, QComboBox, QLabel, QLineEdit, 
                            QPushButton, QFrame, QHeaderView, QGroupBox, QGridLayout, QSplitter)
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QSize
from PyQt5.QtGui import QFont, QColor
from PyQt5.QtGui import QStandardItemModel, QStandardItem
class Ui_MainWindow(object):
    def __init__(self,n_c,n_m):
        self.n_camera = [n_c] if isinstance(n_c, str) else n_c
        self.n_model = [n_m] if isinstance(n_m, str) else n_m

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1801, 1009)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 580))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.automation_table = QtWidgets.QTableWidget(self.frame_2)
        self.automation_table.setMaximumSize(QtCore.QSize(16777215, 550))
        self.automation_table.setObjectName("tableWidget")
        self.setup_automation_table()
        self.verticalLayout_2.addWidget(self.automation_table)


        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        

        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_3)
        self.tableWidget_2.setMaximumSize(QtCore.QSize(16777215, 280))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget_2)



        self.gridLayout.addWidget(self.frame_3, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1801, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "AUTOMATION SETTING CAMERA"))

    def setup_automation_table(self):
        # Configure table properties
        self.automation_table.setRowCount(8)
        self.automation_table.setColumnCount(8)
        
        subheaders = ["", "Camera", "Number of Model", "Variable", "Register", "Assign Value", "Register", "Assign Value"]
        
        # Create merged header for Read/Write
        self.automation_table.setSpan(0, 4, 1, 2)  # Merge cells for "Read"
        self.automation_table.setSpan(0, 6, 1, 2)  # Merge cells for "Write"
        
        # Set read/write headers
        read_header = QTableWidgetItem("Read")
        read_header.setTextAlignment(Qt.AlignCenter)
        read_header.setBackground(QColor(220, 220, 220))
        self.automation_table.setItem(0, 4, read_header)
        
        write_header = QTableWidgetItem("Write")
        write_header.setTextAlignment(Qt.AlignCenter)
        write_header.setBackground(QColor(220, 220, 220))
        self.automation_table.setItem(0, 6, write_header)
        
        # Set subheaders
        for i, subheader in enumerate(subheaders):
            if i < len(subheaders):
                subheader_item = QTableWidgetItem(subheader)
                subheader_item.setTextAlignment(Qt.AlignCenter)
                subheader_item.setBackground(QColor(240, 240, 240))
                self.automation_table.setItem(1, i, subheader_item)
        
        automation_item = QTableWidgetItem("Automation 1")
        automation_item.setTextAlignment(Qt.AlignCenter)
        self.automation_table.setItem(2, 0, automation_item)
        self.automation_table.setSpan(2, 0, 10, 1)  # Merge cells vertically
        
        camera_combo = QComboBox()
        camera_combo.addItems(self.n_camera)
        self.automation_table.setCellWidget(2, 1, camera_combo)
        self.automation_table.setSpan(2, 1, 10, 1)  
        
        model_combo = QComboBox()
        model_combo.addItems(self.n_model)
        self.automation_table.setCellWidget(2, 2, model_combo)
        self.automation_table.setSpan(2, 2, 10, 1)
        
        variables = ["Ready", "Run", "Trigger", "Busy", "Gate", "Complete", "Reset", 
                     "Reset Counter"]
        
        for i, variable in enumerate(variables):
            var_item = QTableWidgetItem(variable)
            var_item.setTextAlignment(Qt.AlignCenter)
            if variable == "Numbers of Shots":
                var_item.setForeground(QColor(0, 0, 255))
            self.automation_table.setItem(i + 2, 3, var_item)
        
        self.automation_table.setItem(2, 4, QTableWidgetItem("ex: DM21423"))
        self.automation_table.setItem(2, 5, QTableWidgetItem("1"))
        self.automation_table.setItem(2, 6, QTableWidgetItem("ex: DM21425"))
        self.automation_table.setItem(2, 7, QTableWidgetItem("1"))

        # No need for model with QTableWidget
        self.automation_table.horizontalHeader().setVisible(False)
        self.automation_table.verticalHeader().setVisible(False)
        self.automation_table.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        
        self.automation_table.setEditTriggers(QTableWidget.NoEditTriggers)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow('1','2')
    ui.setupUi(MainWindow)
    print(ui.automation_table.item(2, 4).text())
    MainWindow.show()
    sys.exit(app.exec_())
