# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys,os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
import mysql.connector
from mysql.connector import Error
from PyQt5.QtWidgets import (QApplication, QMainWindow, QWidget, QLabel, QLineEdit, 
                             QVBoxLayout, QHBoxLayout, QGridLayout, QPushButton, 
                             QFrame, QComboBox, QScrollArea, QMessageBox, QSpinBox,
                             QTabWidget, QTableWidget, QTableWidgetItem, QHeaderView,
                             QGroupBox)
from PyQt5 import QtCore, QtGui, QtWidgets
from module_1.non_layout_itemcode import Pyuic5

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        self.menuOperator = QtWidgets.QMenu(self.menubar)
        self.menuOperator.setObjectName("menuOperator")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionabc = QtWidgets.QAction(MainWindow)
        self.actionabc.setObjectName("actionabc")
        self.actiondevice_configuration_settings = QtWidgets.QAction(MainWindow)
        self.actiondevice_configuration_settings.setObjectName("actiondevice_configuration_settings")
        self.actionDevice_Name = QtWidgets.QAction(MainWindow)
        self.actionDevice_Name.setObjectName("actionDevice_Name")
        self.menuOpen.addAction(self.actiondevice_configuration_settings)
        self.menuOperator.addAction(self.actionDevice_Name)
        self.menubar.addAction(self.menuOpen.menuAction())
        self.menubar.addAction(self.menuOperator.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.menuOperator.setTitle(_translate("MainWindow", "Operator"))
        self.actionabc.setText(_translate("MainWindow", "abc"))
        self.actiondevice_configuration_settings.setText(_translate("MainWindow", "Device Config Setting"))
        self.actionDevice_Name.setText(_translate("MainWindow", "Query Device"))
    
    def closeEvent(self, event):
        reply = QMessageBox.question(
            self,
            "Xác nhận thoát",
            "Bạn có chắc chắn muốn thoát?",
            QMessageBox.Yes | QMessageBox.No,
            QMessageBox.No
        )
        if reply == QMessageBox.Yes:
            print("Đang thoát chương trình...")
            event.accept()
        else:
            event.ignore() 

class main_pyuic:
    
    def __init__(self):
        import sys
        app = QtWidgets.QApplication(sys.argv)
        app.setStyle('Fusion')
        MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(MainWindow)
        MainWindow.show()
        self.ui.actiondevice_configuration_settings.triggered.connect(lambda: self.open_pyuic5())
        sys.exit(app.exec_())

    def open_pyuic5(self):
        self.ui.pyuic5_window = Pyuic5(self.ui)
   
if __name__ == "__main__":
    main_pyuic()