# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_cameratab.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from form_mysql.layout_modeltab import Ui_MainWindow as Ui_ModelTab

class Ui_MainWindow(object):
    def __init__(self):
        self.camera_tabs = {}

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 488)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_quanty_camera = QtWidgets.QFrame(self.frame)
        self.frame_quanty_camera.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.frame_quanty_camera.setFont(font)
        self.frame_quanty_camera.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_quanty_camera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_quanty_camera.setObjectName("frame_quanty_camera")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_quanty_camera)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_name_itemcode = QtWidgets.QLabel(self.frame_quanty_camera)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_name_itemcode.setFont(font)
        self.label_name_itemcode.setObjectName("label_name_itemcode")
        self.gridLayout_2.addWidget(self.label_name_itemcode, 0, 0, 1, 1)
        self.lineEdit_name_itemcod = QtWidgets.QLineEdit(self.frame_quanty_camera)
        self.lineEdit_name_itemcod.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_name_itemcod.setFont(font)
        self.lineEdit_name_itemcod.setObjectName("lineEdit_name_itemcod")
        self.gridLayout_2.addWidget(self.lineEdit_name_itemcod, 0, 1, 1, 1)
        self.label_quanty_camera = QtWidgets.QLabel(self.frame_quanty_camera)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_quanty_camera.setFont(font)
        self.label_quanty_camera.setObjectName("label_quanty_camera")
        self.gridLayout_2.addWidget(self.label_quanty_camera, 1, 0, 1, 1)
        self.spinBox_quanty_cam = QtWidgets.QSpinBox(self.frame_quanty_camera)
        self.spinBox_quanty_cam.setMaximumSize(QtCore.QSize(16777215, 30))
        self.spinBox_quanty_cam.setValue(1)
        self.spinBox_quanty_cam.valueChanged.connect(self.update_quanty_models)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox_quanty_cam.setFont(font)
        self.spinBox_quanty_cam.setObjectName("spinBox_quanty_cam")
        self.gridLayout_2.addWidget(self.spinBox_quanty_cam, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_quanty_camera, 0, 0, 1, 1)
        self.tab_camera = QtWidgets.QTabWidget(self.frame)
        self.tab_camera.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tab_camera.setFont(font)
        self.tab_camera.setObjectName("tab_camera")

        self.gridLayout_4.addWidget(self.tab_camera, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_camera.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.update_quanty_models()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name_itemcode.setText(_translate("MainWindow", "Tên mã hàng :"))
        self.label_quanty_camera.setText(_translate("MainWindow", "Số lượng camera:"))

    
    def update_quanty_models(self):
        self.tab_camera.clear()
        self.camera_tabs_list = []
        for i in range(self.spinBox_quanty_cam.value()):
            self.core_ui = QtWidgets.QMainWindow()
            self.tab_model_1 = Ui_ModelTab()
            self.tab_model_1.setupUi(self.core_ui)
            self.camera_tabs_list.append(self.tab_model_1)
            self.tab_camera.addTab(self.core_ui, f'Camera {i+1}')

    def get_data(self):
        data = {}
        for i in range(self.tab_camera.count()):
            camera_tab = self.tab_camera.widget(i)
            camera_name = camera_tab.lineEdit_name_itemcod.text()
            model_data = camera_tab.get_data()
            data[camera_name] = model_data
        return data
    
    def take_data(self):
        return {
            "product_codes": self.lineEdit_name_itemcod.text(),
            "camera_tabs": [form.get_data() for form in self.camera_tabs_list]
        }
